version: '3.5'

networks:
    servicesnet:
        name: networkservices
        driver: bridge

services:
    php:
        build:
            context: ./docker/files/php
            dockerfile: Dockerfile
        container_name: phpsvr
        networks:
            - servicesnet